version: '3.5'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./Nginx_Mosq/mosquitto/config:/mosquitto/config
      - ./Nginx_Mosq/mosquitto/data:/mosquitto/data
      - ./Nginx_Mosq/mosquitto/passwd:/etc/mosquitto/passwd
      - ./Nginx_Mosq/mosquitto/mosquitto.acl:/etc/mosquitto/mosquitto.acl
      - ./logs/mosquitto/:/mosquitto/log
    networks:
      - mosquitto-net

  proxy1:
    container_name: proxy1
    image: nginx:stable
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx_Mosq/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    networks:
      - mosquitto-net

networks:
  mosquitto-net:

